spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?user=root&password=wufulin&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /manager
  port: 8081